---
- name: cisco-show_cdp_neighbors
  hosts: all
  gather_facts: no
  ignore_errors: true
  tasks:
   - name: run show data collection commands on ios device
     ios_command:
       commands:
         - show cdp neighbors
         - show interface trunk
         - show interface description
         - show interface | grep gi/52
