---
- hosts: all
  gather_facts: false
  tasks:
    - name: ping command
      delegate_to: localhost
      shell: "ping -c4 {{ inventory_hostname[1] }} "
      register: out
      ignore_errors: yes

    - meta: clear_host_errors

    - name: standard out
      debug:
        msg: "{{ out.stdout_lines }}"

    - name: return code
      debug:
        msg: "{{ out.rc }}"

    - name: failed ping
      debug:
        msg: "{{ inventory_hostname }} has 100% packet loss"
      when: "out.stdout_lines is search ('100% packet loss')"
